### ISSUE TITLE
Only some are working

### ISSUE THREAD

**Issue by tomtommi12** [HeathLoganCampbell/MinecraftBut#14]
I have a normal set up server but only the bedrock trail and the health and jumping ones do work

**Comment by HeathLoganCampbell** [comment]
What version of spigot  are you running?

**Comment by Heesel** [comment]
yeah, im using 1.8 and they don't work. (Bedrock trail, health and jumping)

**Comment by HeathLoganCampbell** [comment]
May you  paste your console log? @Heesel

**Comment by Heesel** [comment]
23.12 15:22:27 [Server] INFO [MinecraftBut]'Bedrock Trail' has been Enabled
oh and can i ask you something. Could you add that when ever you touch something with your hand it turns into bedrock? and also when you walk it turns into bedrock

**Comment by HeathLoganCampbell** [comment]
@Heesel I need the WHOLE console log, of everything
and sure

**Comment by Heesel** [comment]
25.12 02:20:14 [Server] INFO Replace Blocks: [1, 5]
25.12 02:20:14 [Server] INFO Nerfing mobs spawned from spawners: false
25.12 02:20:14 [Server] INFO Cactus Growth Modifier: 100%
25.12 02:20:14 [Server] INFO Cane Growth Modifier: 100%
25.12 02:20:14 [Server] INFO Melon Growth Modifier: 100%
25.12 02:20:14 [Server] INFO Mushroom Growth Modifier: 100%
25.12 02:20:14 [Server] INFO Pumpkin Growth Modifier: 100%
25.12 02:20:14 [Server] INFO Sapling Growth Modifier: 100%
25.12 02:20:14 [Server] INFO Wheat Growth Modifier: 100%
25.12 02:20:14 [Server] INFO Entity Activation Range: An 32 / Mo 32 / Mi 16
25.12 02:20:14 [Server] INFO Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
25.12 02:20:14 [Server] INFO Alternative Hopper Ticking: false
25.12 02:20:14 [Server] INFO Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
25.12 02:20:14 [Server] INFO Random Lighting Updates: false
25.12 02:20:14 [Server] INFO Structure Info Saving: true
25.12 02:20:14 [Server] INFO Sending up to 10 chunks per packet
25.12 02:20:14 [Server] INFO Max Entity Collisions: 8
25.12 02:20:14 [Server] INFO Custom Map Seeds: Village: 10387312 Feature: 14357617
25.12 02:20:14 [Server] INFO Max TNT Explosions: 100
25.12 02:20:14 [Server] INFO Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
25.12 02:20:14 [Server] INFO Item Despawn Rate: 6000
25.12 02:20:14 [Server] INFO Item Merge Radius: 2.5
25.12 02:20:14 [Server] INFO Arrow Despawn Rate: 1200
25.12 02:20:14 [Server] INFO Allow Zombie Pigmen to spawn from portal blocks: true
25.12 02:20:14 [Server] INFO View Distance: 10
25.12 02:20:14 [Server] INFO Zombie Aggressive Towards Villager: true
25.12 02:20:14 [Server] INFO Chunks to Grow per Tick: 650
25.12 02:20:14 [Server] INFO Clear tick list: false
25.12 02:20:14 [Server] INFO Experience Merge Radius: 3.0
25.12 02:20:14 [Server] INFO Preparing start region for level 0 (Seed: 465562412883324160)
25.12 02:20:15 [Server] INFO Preparing spawn area: 16%
25.12 02:20:16 [Server] INFO Preparing spawn area: 94%
25.12 02:20:16 [Server] INFO Preparing start region for level 1 (Seed: 465562412883324160)
25.12 02:20:17 [Server] INFO Preparing start region for level 2 (Seed: 465562412883324160)
25.12 02:20:18 [Server] INFO [WorldEdit] Enabling WorldEdit v6.1;no_git_id
25.12 02:20:18 [Server] INFO WEPIF: Using the Bukkit Permissions API.
25.12 02:20:18 [Server] INFO [WorldEdit] Using com.sk89q.worldedit.bukkit.adapter.impl.Spigot_v1_8_R1 as the Bukkit adapter
25.12 02:20:18 [Server] INFO [Skript] Enabling Skript v2.4
25.12 02:20:19 [Server] ERROR Error occurred while enabling Skript v2.4 (Is it up to date?)
25.12 02:20:19 [Server] INFO java.lang.NoClassDefFoundError: com/google/gson/GsonBuilder
25.12 02:20:19 [Server] INFO at ch.njol.skript.update.ReleaseManifest.load(ReleaseManifest.java:54) ~[?:?]
25.12 02:20:19 [Server] INFO at ch.njol.skript.SkriptUpdater.loadManifest(SkriptUpdater.java:79) ~[?:?]
25.12 02:20:19 [Server] INFO at ch.njol.skript.SkriptUpdater.<init>(SkriptUpdater.java:62) ~[?:?]
25.12 02:20:19 [Server] INFO at ch.njol.skript.Skript.onEnable(Skript.java:310) ~[?:?]
25.12 02:20:19 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot-1.8.jar:git-Spigot-550ebac-7019900]
25.12 02:20:19 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
25.12 02:20:19 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
25.12 02:20:19 [Server] INFO at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugin(CraftServer.java:356) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
25.12 02:20:19 [Server] INFO at org.bukkit.craftbukkit.v1_8_R1.CraftServer.enablePlugins(CraftServer.java:316) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
25.12 02:20:19 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.q(MinecraftServer.java:402) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
25.12 02:20:19 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.k(MinecraftServer.java:370) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
25.12 02:20:19 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.a(MinecraftServer.java:325) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
25.12 02:20:19 [Server] INFO at net.minecraft.server.v1_8_R1.DedicatedServer.init(DedicatedServer.java:211) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
25.12 02:20:19 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:505) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
25.12 02:20:19 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
25.12 02:20:19 [Server] INFO Caused by: java.lang.ClassNotFoundException: com.google.gson.GsonBuilder
25.12 02:20:19 [Server] INFO at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_222]
25.12 02:20:19 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot-1.8.jar:git-Spigot-550ebac-7019900]
25.12 02:20:19 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.8.jar:git-Spigot-550ebac-7019900]
25.12 02:20:19 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_222]
25.12 02:20:19 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_222]
25.12 02:20:19 [Server] INFO ... 15 more
25.12 02:20:19 [Server] INFO [MinecraftBut] Enabling MinecraftBut v0.0.1-SNAPSHOT
25.12 02:20:19 [Server] INFO [Essentials] Enabling Essentials v2.0.1-b245
25.12 02:20:19 [Server] INFO Using locale en_US
25.12 02:20:19 [Server] INFO [Essentials] Using CraftBukkit 1.8 NMS-based provider as spawner provider.
25.12 02:20:19 [Server] INFO Using locale en_US
25.12 02:20:19 [Server] INFO [Essentials] Starting Metrics. Opt-out using the global PluginMetrics config.
25.12 02:20:19 [Server] INFO [Essentials] Using config file enhanced permissions.
25.12 02:20:19 [Server] INFO [Essentials] Permissions listed in as player-commands will be given to all users.
25.12 02:20:19 [Server] INFO Server permissions file permissions.yml is empty, ignoring it
25.12 02:20:19 [Server] Startup Done (6.102s)! For help, type "help" or "?"
25.12 20:35:00 [Server] INFO UUID of player heesel is 414bbaee-3ad6-4110-aaa2-dd0c05befbe0
25.12 20:35:00 [Server] WARN java.lang.ArrayIndexOutOfBoundsException: 0
25.12 20:35:00 [Server] WARN at games.bevs.minecraftbut.commons.TabUtils.sendTab(TabUtils.java:24)
25.12 20:35:00 [Server] WARN at games.bevs.minecraftbut.listeners.WelcomeListener.onJoin(WelcomeListener.java:34)
25.12 20:35:00 [Server] WARN at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
25.12 20:35:00 [Server] WARN at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
25.12 20:35:00 [Server] WARN at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
25.12 20:35:00 [Server] WARN at java.lang.reflect.Method.invoke(Method.java:498)
25.12 20:35:00 [Server] WARN at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301)
25.12 20:35:00 [Server] WARN at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
25.12 20:35:00 [Server] WARN at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
25.12 20:35:00 [Server] WARN at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
25.12 20:35:00 [Server] WARN at net.minecraft.server.v1_8_R1.PlayerList.onPlayerJoin(PlayerList.java:272)
25.12 20:35:00 [Server] WARN at net.minecraft.server.v1_8_R1.PlayerList.a(PlayerList.java:156)
25.12 20:35:00 [Server] WARN at net.minecraft.server.v1_8_R1.LoginListener.b(LoginListener.java:109)
25.12 20:35:00 [Server] WARN at net.minecraft.server.v1_8_R1.LoginListener.c(LoginListener.java:41)
25.12 20:35:00 [Server] WARN at net.minecraft.server.v1_8_R1.NetworkManager.a(NetworkManager.java:159)
25.12 20:35:00 [Server] WARN at net.minecraft.server.v1_8_R1.ServerConnection.c(ServerConnection.java:82)
25.12 20:35:00 [Server] WARN at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:800)
25.12 20:35:00 [Server] WARN at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316)
25.12 20:35:00 [Server] WARN at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634)
25.12 20:35:00 [Server] WARN at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537)
25.12 20:35:00 [Server] WARN at java.lang.Thread.run(Thread.java:748)
25.12 20:35:00 [Connect] User heesel, (IP hidden) 
25.12 20:35:00 [PebbleHost] heesel ran command Message of the Day
25.12 20:35:05 [Server] INFO heesel issued server command: /mb
25.12 20:35:07 [Server] INFO heesel issued server command: /mb
25.12 20:35:09 [Server] INFO [MinecraftBut]'Bedrock Trail' has been Enabled

**Comment by Heesel** [comment]
i fixed it, problem was that i was in creative all the time :)
